import './supportstyle.css';
function Support() {
    return(
        <div className="main__text"><img className = "card_pic1" src ="https://placekitten.com/200/600" alt="Card Cats" align="left"/>
         <p className="support__text">Lorem ipsum dolor sit amet,cons adipiscing elit.Ut enim ad minim veniam, quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu
         Lorem ipsum dolor sit amet quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu fugiat nulla pariahgtur
         cons adipiscing elit.Ut enim ad minim veniam, quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu fugiat nulla pariahgtur</p>
        <p>Plays league of legends stare out the window. Lies down lick sellotape hopped up on catnip, yet bleghbleghvomit my furball really tie the room together, thug cat . Play riveting piece on synthesizer keyboard sit in window and stare oooh, a bird, yum shove bum in owner’s face like camera lens or toy mouse squeak roll over. Fall asleep on the washing machine hide when guests come over stare at guinea pigs yet vommit food and eat it again eat and than sleep on your face. Jump five feet high and sideways when a shadow moves throwup on your pillow. Missing until dinner time. Pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now nap all day flop over, so missing until dinner time, for see owner, run in terror sun bathe. Give attitude intently sniff hand, yet meow all night having their mate disturbing sleeping humans.</p>
       <div className="between_line"></div>
        <img className = "card_pic1" src ="https://placekitten.com/300/600" alt="Card Cats" align="left"/>
         <p className="support__text">Lorem ipsum dolor sit amet,cons adipiscing elit.Ut enim ad minim veniam, quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu
         Lorem ipsum dolor sit amet quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu fugiat nulla pariahgtur
         cons adipiscing elit.Ut enim ad minim veniam, quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu fugiat nulla pariahgtur</p>
        <p>Plays league of legends stare out. Lies down lick sellotape hopped up on catnip, yet bleghbleghvomit my furball really tie the room together, thug cat . Play riveting piece on synthesizer keyboard sit in window and stare oooh, a bird, yum shove bum in owner’s face like camera lens or toy mouse squeak roll over. Fall asleep on the washing machine hide when guests come over stare at guinea pigs yet vommit food and eat it again eat and than sleep on your face. Jump five feet high and sideways when a shadow moves throwup on your pillow. Missing until dinner time. Pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now nap all day flop over.</p>
        <div className="between_line"></div>
        <img className = "card_pic1" src ="https://placekitten.com/400/500" alt="Card Cats" align="left"/>
         <p className="support__text">Lorem ipsum dolor sit amet,cons adipiscing elit.Ut enim ad minim veniam, quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu
         Lorem ipsum dolor sit amet quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu fugiat nulla pariahgtur
         cons adipiscing elit.Ut enim ad minim veniam, quistydfhf jkiojjk nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptaghffte velit esse cillum dolore eu fugiat nulla pariahgtur</p>
        <p>Plays league of legends stare out the window. Lies down lick sellotape hopped up on catnip, yet bleghbleghvomit my furball really tie the room together, thug cat . Play riveting piece on synthesizer keyboard sit in window and stare oooh, a bird, yum shove bum in owner’s face like camera lens or toy mouse squeak roll over. Fall asleep on the washing machine hide when guests come over stare at guinea pigs yet vommit food and eat it again eat and than sleep on your face. Jump five feet high and sideways when a shadow moves throwup on your pillow. Missing until dinner time. Pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now nap all day flop over, so missing until dinner time, for see owner, run in terror sun bathe. Give attitude intently sniff hand, yet meow all night having their mate disturbing sleeping humans.</p>
        </div>
    );
}
export default Support;